### ISSUE TITLE
Very low FPS after Getting CV'd by dragon

### ISSUE THREAD

**Issue by without-ordinary** [Archival1/CV-BugReporting#18]
**Describe the bug**
After getting DV'd by the City dragon, FPS drops to 5-6 and CPU load is pegged (possible to 100% single core).

**To Reproduce**
1. Load City
2. Get CV'd by dragon
3. Have dragon's balls on screen
4. Enjoy slideshow

**Expected behavior**
Not have massive performance impact while CV'd.

**Screenshots**
The default Stream screenshot does not capture the overlay, so nothing to see.

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Graphics Card: AMD, Steam Deck non-OLED
 - Version: 1/19/2024_cef91e5c

**Additional context**
If something blocks the camera's view of the dragon and causes culling, the issue stops.

Saw this reported a few times on the Discord. Was able to repo on my Deck while testing other things.

**Comment by naelstrof** [comment]
Turns out it was a bug with Unity's input system, as soon as the player is removed it spams Navigate events 50 times a frame. Player input isn't even on the player so I'm not sure why it happens.

The lag is from me searching for navigable UI on each event, it only does this if nothing is currently selected. Since there's no UI to select, it just does this 50 times a frame.

Was hard to figure out as I had to do some remote profiling as this bug doesn't trigger at all on PC. Got it fixed as of 9853802d
